### ISSUE TITLE
Задача 1. Прочитать файл README.md и добавить имя и логины разработчика, под соответствующим номером: your_name - your_login

### ISSUE THREAD

**Issue by 555-F-a-r-id-555** [Seminar-git-DZ-3/sem3-dz-3#1]
Задача 1. Прочитать файл README.md и добавить имя и логины разработчика, под соответствующим номером: your_name - your_login

**Comment by Smazhko** [comment]
принял в работу @555-F-a-r-id-555

**Comment by Smazhko** [comment]
готово @555-F-a-r-id-555. проверь, пожалста

**Comment by 555-F-a-r-id-555** [comment]
Спасибо, @Smazhko - отлично молодец ^v^
