### ISSUE TITLE
Добавить эффекты наведения (hover) для кнопки и textarea в  HTML и CSS файлы 

### ISSUE THREAD

**Issue by 555-F-a-r-id-555** [Seminar-git-DZ-3/sem3-dz-3#11]
Добавить эффекты наведения (hover) для кнопки и textarea в  HTML и CSS файлы

**Comment by wwwFredwww** [comment]
Задание принял @555-F-a-r-id-555

**Comment by wwwFredwww** [comment]
Задание выполнил @555-F-a-r-id-555
