### ISSUE TITLE
Создать файл WISHES.md

### ISSUE THREAD

**Issue by 555-F-a-r-id-555** [Seminar-git-DZ-3/sem3-dz-3#2]
Создать файл WISHES.md

**Comment by Smazhko** [comment]
уважаемый @555-F-a-r-id-555 , принял в работу 💯  10,39.

**Comment by Smazhko** [comment]
задание выполнено. файл wishes.md создан //10.47

**Comment by 555-F-a-r-id-555** [comment]
Спасибо, принял @Smazhko все отлично молодец
