### ISSUE TITLE
Протестировать работу чата и написать свои замечания и пожелания в файл WISHES.md

### ISSUE THREAD

**Issue by 555-F-a-r-id-555** [Seminar-git-DZ-3/sem3-dz-3#3]
Протестировать работу чата и написать свои замечания и пожелания в файл WISHES.md

**Comment by 555-F-a-r-id-555** [comment]
Уважаемые разработчики, @Smazhko @ZoxPapa  оставьте свои комментарии в файле WISHES.md

**Comment by wwwFredwww** [comment]
задание принял @555-F-a-r-id-555

**Comment by wwwFredwww** [comment]
задание выполнено @555-F-a-r-id-555

**Comment by Smazhko** [comment]
@555-F-a-r-id-555 задача выполнена. пожелания размещены в файле WISHES.md
