### ISSUE TITLE
При желании, изменить цвет кнопки и фона по своему усмотрению

### ISSUE THREAD

**Issue by 555-F-a-r-id-555** [Seminar-git-DZ-3/sem3-dz-3#4]
При желании, изменить цвет кнопки и фона по своему усмотрению

**Comment by 555-F-a-r-id-555** [comment]
изменить, в файле style.scc на строке 9 background-color: aquamarine; (на любой цвет, например chartreuse) и в строке 56 background-color: blueviolet;  (на любой цвет, например mediumseagreen)

**Comment by ZoxPapa** [comment]
Приступил к выполнению.

**Comment by ZoxPapa** [comment]
@555-F-a-r-id-555  Colors are switched. Issue is complete.

**Comment by 555-F-a-r-id-555** [comment]
Спасибо @ZoxPapa,   pull request принят
