### ISSUE TITLE
Добавить имя или логины разработчика, в файл README.md под соответствующим номером: your_name - your_login

### ISSUE THREAD

**Issue by 555-F-a-r-id-555** [Seminar-git-DZ-3/sem3-dz-3#7]
Добавить имя или логины разработчика ,  в файл README.md под соответствующим номером: your_name - your_login

**Comment by ZoxPapa** [comment]
Starting the issue.

**Comment by ZoxPapa** [comment]
@555-F-a-r-id-555 , @Smazhko There are no your LogIns in the rows 15, 16. Right format: your_name - your_login.

**Comment by ZoxPapa** [comment]
@555-F-a-r-id-555 Issue complete. Thanks for teamwork.

**Comment by 555-F-a-r-id-555** [comment]
Спасибо @ZoxPapa,   pull request принят

**Comment by Smazhko** [comment]
@555-F-a-r-id-555 выполнена  коррекция. добавлен @никнейм в файл. создан pull-request
